"""init item

Revision ID: 370a78ff2c0f
Revises: 
Create Date: 2024-07-02 21:08:13.536194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '370a78ff2c0f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('foo', sa.Integer(), nullable=False),
    sa.Column('bar', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_items')),
    sa.UniqueConstraint('foo', 'bar', name=op.f('uq_items_foo_bar')),
    sa.UniqueConstraint('name', name=op.f('uq_items_name'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items')
    # ### end Alembic commands ###
